/**
 * Open API Demo - REST APIs
 * Demonstration about Open API and Spring Restful.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ResponseStatus = 'OK' | 'BAD_REQUEST' | 'UNAUTHORIZED' | 'VALIDATION_EXCEPTION' | 'EXCEPTION' | 'WRONG_CREDENTIALS' | 'ACCESS_DENIED' | 'NOT_FOUND' | 'DUPLICATE_ENTITY';

export const ResponseStatus = {
    OK: 'OK' as ResponseStatus,
    BADREQUEST: 'BAD_REQUEST' as ResponseStatus,
    UNAUTHORIZED: 'UNAUTHORIZED' as ResponseStatus,
    VALIDATIONEXCEPTION: 'VALIDATION_EXCEPTION' as ResponseStatus,
    EXCEPTION: 'EXCEPTION' as ResponseStatus,
    WRONGCREDENTIALS: 'WRONG_CREDENTIALS' as ResponseStatus,
    ACCESSDENIED: 'ACCESS_DENIED' as ResponseStatus,
    NOTFOUND: 'NOT_FOUND' as ResponseStatus,
    DUPLICATEENTITY: 'DUPLICATE_ENTITY' as ResponseStatus
};

