/**
 * Open API Demo - REST APIs
 * Demonstration about Open API and Spring Restful.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskStatus } from './taskStatus';


export interface TaskDto { 
    id: string;
    title: string;
    content?: string;
    level?: number;
    taskStatus?: TaskStatus;
    start: string;
    end: string;
}

