/**
 * Open API Demo - REST APIs
 * Demonstration about Open API and Spring Restful.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TaskStatus = 'IN_QUEUE' | 'IN_PROGRESS' | 'FINISHED';

export const TaskStatus = {
    INQUEUE: 'IN_QUEUE' as TaskStatus,
    INPROGRESS: 'IN_PROGRESS' as TaskStatus,
    FINISHED: 'FINISHED' as TaskStatus
};

